// Livello di potenza dei brawler del proprietario dell'app.
// GENERATO da script/fetch-profilo-brawl.js — non modificare a mano.
// Letto il 2026-09-09 dal tracker pubblico di brawlplanet.
//
// Per ogni brawler: livello di potenza, trofei, e quali gadget e star power
// sono gia' posseduti (e quali mancano, col loro costo in monete).
//
// PERCHÉ SERVE: in Classificata un brawler sotto POTENZA 9 non si può
// schierare, e da Mythic in su ne serve uno a POTENZA 11. Un consiglio su un
// brawler che non puoi mettere in campo è peggio che inutile: fa perdere i
// secondi che non hai. Qui ce ne sono 50 giocabili su 106, 36 a potenza 11.
//
// Il tag del giocatore NON sta qui apposta: questo repository è pubblico.
// È una fotografia: risbloccando o potenziando un brawler va rilanciato.
const PROFILO = {
  "8-Bit": { potenza: 11, trofei: 1000, gadget: ["Cheat Cartridge"], starPower: ["Boosted Booster","Plugged In"], gadgetMancanti: ["Extra Credits"], starPowerMancanti: [] },
  "Alli": { potenza: 1, trofei: 13, gadget: [], starPower: [], gadgetMancanti: ["Feed The Gators","Cold-Blooded"], starPowerMancanti: ["Lizard Limbs","You Better Run, You Better Take Cover"] },
  "Amber": { potenza: 9, trofei: 1000, gadget: ["Fire Starters","Dancing Flames"], starPower: ["Wild Flames","Scorchin' Siphon"], gadgetMancanti: [], starPowerMancanti: [] },
  "Angelo": { potenza: 7, trofei: 375, gadget: ["Stinging Flight","Master Fletcher"], starPower: [], gadgetMancanti: [], starPowerMancanti: ["Empower","Flow"] },
  "Ash": { potenza: 9, trofei: 46, gadget: ["Chill Pill"], starPower: ["First Bash"], gadgetMancanti: ["Rotten Banana"], starPowerMancanti: ["Mad As Heck"] },
  "Barley": { potenza: 1, trofei: 124, gadget: [], starPower: [], gadgetMancanti: ["Sticky Syrup Mixer","Herbal Tonic"], starPowerMancanti: ["Medical Use","Extra Noxious"] },
  "Bea": { potenza: 10, trofei: 1362, gadget: ["Honey Molasses","Rattled Hive"], starPower: ["Insta Beaload","Honeycomb"], gadgetMancanti: [], starPowerMancanti: [] },
  "Belle": { potenza: 9, trofei: 1006, gadget: ["Nest Egg","Reverse Polarity"], starPower: ["Positive Feedback","Grounded"], gadgetMancanti: [], starPowerMancanti: [] },
  "Berry": { potenza: 1, trofei: 33, gadget: [], starPower: [], gadgetMancanti: ["Friendship Is Great","Healthy Additives"], starPowerMancanti: ["Floor Is Fine","Making A Mess"] },
  "Bibi": { potenza: 1, trofei: 171, gadget: [], starPower: [], gadgetMancanti: ["Vitamin Booster","Extra Sticky"], starPowerMancanti: ["Home Run","Batting Stance"] },
  "Bo": { potenza: 11, trofei: 2012, gadget: ["Super Totem","Tripwire"], starPower: ["Circling Eagle","Snare A Bear"], gadgetMancanti: [], starPowerMancanti: [] },
  "Bolt": { potenza: 8, trofei: 10, gadget: [], starPower: [], gadgetMancanti: ["Oil Change","Bouncy Ball"], starPowerMancanti: ["Toss Up","Unstoppaball"] },
  "Bonnie": { potenza: 1, trofei: 46, gadget: [], starPower: [], gadgetMancanti: ["Sugar Rush","Crash Test"], starPowerMancanti: ["Black Powder","Wisdom Tooth"] },
  "Brock": { potenza: 11, trofei: 2003, gadget: ["Rocket Laces","Rocket Fuel"], starPower: ["More Rockets!","Rocket No. 4"], gadgetMancanti: [], starPowerMancanti: [] },
  "Bull": { potenza: 9, trofei: 1005, gadget: ["T-Bone Missile","Stomper"], starPower: ["Berserker","Tough Guy"], gadgetMancanti: [], starPowerMancanti: [] },
  "Buster": { potenza: 7, trofei: 53, gadget: ["Utility Belt","Slo-Mo Replay"], starPower: [], gadgetMancanti: [], starPowerMancanti: ["Blockbuster","Kevlar Vest"] },
  "Buzz": { potenza: 10, trofei: 1006, gadget: ["Reserve Buoy","X-Ray-Shades"], starPower: ["Tougher Torpedo","Eyes Sharp"], gadgetMancanti: [], starPowerMancanti: [] },
  "Byron": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Shot In The Arm","Booster Shots"], starPowerMancanti: ["Malaise","Injection"] },
  "Carl": { potenza: 11, trofei: 1006, gadget: ["Heat Ejector","Flying Hook"], starPower: ["Power Throw","Protective Pirouette"], gadgetMancanti: [], starPowerMancanti: [] },
  "Charlie": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Spiders","Personal Space"], starPowerMancanti: ["Digestive","Slimy"] },
  "Chester": { potenza: 11, trofei: 1821, gadget: ["Spicy Dice","Candy Beans"], starPower: ["Single Bell'o'mania","Sneak Peek"], gadgetMancanti: [], starPowerMancanti: [] },
  "Chuck": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Rerouting","Ghost Train"], starPowerMancanti: ["Pit Stop","Tickets Please!"] },
  "Clancy": { potenza: 6, trofei: 165, gadget: [], starPower: [], gadgetMancanti: ["Snappy Shooting","Tactical Retreat"], starPowerMancanti: ["Recon","Pumping Up"] },
  "Colette": { potenza: 10, trofei: 1057, gadget: ["Na-Ah!","Gotcha!"], starPower: ["Push It","Mass Tax"], gadgetMancanti: [], starPowerMancanti: [] },
  "Colt": { potenza: 11, trofei: 1771, gadget: ["Speedloader","Silver Bullet"], starPower: ["Slick Boots","Magnum Special"], gadgetMancanti: [], starPowerMancanti: [] },
  "Cordelius": { potenza: 11, trofei: 1176, gadget: ["Replanting","Poison Mushroom"], starPower: ["Comboshrooms","Mushroom Kingdom"], gadgetMancanti: [], starPowerMancanti: [] },
  "Crow": { potenza: 11, trofei: 2007, gadget: ["Instapoison","Slowing Toxin"], starPower: ["Extra Toxic","Carrion Crow"], gadgetMancanti: [], starPowerMancanti: [] },
  "Damian": { potenza: 11, trofei: 1357, gadget: ["Spiritual Healing","Wall Of Sound"], starPower: ["Crowdkill","Vulgar Display Of Punch"], gadgetMancanti: [], starPowerMancanti: [] },
  "Darryl": { potenza: 1, trofei: 145, gadget: [], starPower: [], gadgetMancanti: ["Recoiling Rotator","Tar Barrel"], starPowerMancanti: ["Steel Hoops","Rolling Reload"] },
  "Doug": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Double Sausage","Extra Mustard"], starPowerMancanti: ["Fast Food","Self Service"] },
  "Draco": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Upper Cut","Last Stand"], starPowerMancanti: ["Expose","Shredding"] },
  "Dynamike": { potenza: 6, trofei: 150, gadget: [], starPower: [], gadgetMancanti: ["Fidget Spinner","Satchel Charge"], starPowerMancanti: ["Dyna-Jump","Demolition"] },
  "Edgar": { potenza: 11, trofei: 1589, gadget: ["Let's Fly","Hardcore"], starPower: ["Hard Landing","Fisticuffs"], gadgetMancanti: [], starPowerMancanti: [] },
  "El Primo": { potenza: 5, trofei: 248, gadget: [], starPower: [], gadgetMancanti: ["Suplex Supplement","Asteroid Belt"], starPowerMancanti: ["El Fuego","Meteor Rush"] },
  "Emz": { potenza: 11, trofei: 2009, gadget: ["Friendzoner"], starPower: ["Bad Karma","Hype"], gadgetMancanti: ["Acid Spray"], starPowerMancanti: [] },
  "Eve": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Gotta Go!","Motherly Love"], starPowerMancanti: ["Unnatural Order","Happy Surprise"] },
  "Fang": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Corn-Fu","Roundhouse Kick"], starPowerMancanti: ["Fresh Kicks","Divine Soles"] },
  "Finx": { potenza: 1, trofei: 204, gadget: [], starPower: [], gadgetMancanti: ["Back To The Finxture","No Escape"], starPowerMancanti: ["Hieroglyph Halt","Primer"] },
  "Frank": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Active Noise Canceling","Irresistible Attraction"], starPowerMancanti: ["Power Grab","Sponge"] },
  "Gale": { potenza: 10, trofei: 1011, gadget: ["Twister"], starPower: ["Blustery Blow","Freezing Snow"], gadgetMancanti: ["Spring Ejector"], starPowerMancanti: [] },
  "Gene": { potenza: 10, trofei: 1006, gadget: ["Lamp Blowout"], starPower: ["Magic Puffs","Spirit Slap"], gadgetMancanti: ["Vengeful Spirits"], starPowerMancanti: [] },
  "Gigi": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Longer Strings","Disappearing Act"], starPowerMancanti: ["Plié Protection","A Helping Hand"] },
  "Glowy": { potenza: 9, trofei: 820, gadget: ["Slippery Savior","More Lumens!"], starPower: ["Biotic Ecosystem","Parasitism"], gadgetMancanti: [], starPowerMancanti: [] },
  "Gray": { potenza: 11, trofei: 1012, gadget: ["Walking Cane","Grand Piano"], starPower: ["Fake Injury","New Perspective"], gadgetMancanti: [], starPowerMancanti: [] },
  "Griff": { potenza: 11, trofei: 1619, gadget: ["Piggy Bank","Coin Shower"], starPower: ["Keep The Change","Business Resilience"], gadgetMancanti: [], starPowerMancanti: [] },
  "Grom": { potenza: 1, trofei: 131, gadget: [], starPower: [], gadgetMancanti: ["Watchtower","Radio Check"], starPowerMancanti: ["Foot Patrol","X-Factor"] },
  "Gus": { potenza: 11, trofei: 1428, gadget: ["Kooky Popper"], starPower: ["Health Bonanza","Spirit Animal"], gadgetMancanti: ["Knockback Spirit"], starPowerMancanti: [] },
  "Hank": { potenza: 1, trofei: 42, gadget: [], starPower: [], gadgetMancanti: ["Water Balloons","Barricade"], starPowerMancanti: ["It's Gonna Blow","Take Cover!"] },
  "Jacky": { potenza: 1, trofei: 145, gadget: [], starPower: [], gadgetMancanti: ["Pneumatic Booster","Rebuild"], starPowerMancanti: ["Counter Crush","Hardy Hard Hat"] },
  "Jae-Yong": { potenza: 1, trofei: 49, gadget: [], starPower: [], gadgetMancanti: ["Weekend Warrior","Time For A Slow Song"], starPowerMancanti: ["The Crowd Goes Mild","Extra High Note"] },
  "Janet": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Drop The Bass","Backstage Pass"], starPowerMancanti: ["Stage View","Vocal Warm Up"] },
  "Jessie": { potenza: 1, trofei: 145, gadget: [], starPower: [], gadgetMancanti: ["Spark Plug","Recoil Spring"], starPowerMancanti: ["Energize","Shocky"] },
  "Juju": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Voodoo Chile","Elementalist"], starPowerMancanti: ["Guarded Gris-Gris","Numbing Needles"] },
  "Kaze": { potenza: 1, trofei: 60, gadget: [], starPower: [], gadgetMancanti: ["Gracious Host","Hensojutsu"], starPowerMancanti: ["Advanced Techniques","Gratuity Included"] },
  "Kenji": { potenza: 9, trofei: 1001, gadget: ["Dashi Dash","Hosomaki Healing"], starPower: ["Studied The Blade","Nigiri Nemesis"], gadgetMancanti: [], starPowerMancanti: [] },
  "Kit": { potenza: 11, trofei: 1192, gadget: ["Cardboard Box","Cheeseburger"], starPower: ["Power Hungry","Overly Attached"], gadgetMancanti: [], starPowerMancanti: [] },
  "Larry & Lawrie": { potenza: 1, trofei: 206, gadget: [], starPower: [], gadgetMancanti: ["Order: Swap","Order: Fall Back"], starPowerMancanti: ["Protocol: Protect","Protocol: Assist"] },
  "Leon": { potenza: 11, trofei: 2006, gadget: ["Clone Projector","Lollipop Drop"], starPower: ["Smoke Trails","Invisiheal"], gadgetMancanti: [], starPowerMancanti: [] },
  "Lily": { potenza: 7, trofei: 432, gadget: ["Vanish","Repot"], starPower: [], gadgetMancanti: [], starPowerMancanti: ["Spiky","Vigilance"] },
  "Lola": { potenza: 1, trofei: 111, gadget: [], starPower: [], gadgetMancanti: ["Freeze Frame","Stunt Double"], starPowerMancanti: ["Improvise","Sealed With A Kiss"] },
  "Lou": { potenza: 11, trofei: 1042, gadget: ["Ice Block","Cryo Syrup"], starPower: ["Supercool","Hypothermia"], gadgetMancanti: [], starPowerMancanti: [] },
  "Lumi": { potenza: 11, trofei: 2012, gadget: ["Hit The Lights","Grim And Frostbitten"], starPower: ["42% Burnt","Half-Time"], gadgetMancanti: [], starPowerMancanti: [] },
  "Maisie": { potenza: 6, trofei: 227, gadget: [], starPower: [], gadgetMancanti: ["Disengage!","Finish Them!"], starPowerMancanti: ["Pinpoint Precision","Tremors"] },
  "Mandy": { potenza: 9, trofei: 415, gadget: ["Caramelize","Cookie Crumbs"], starPower: ["In My Sights","Hard Candy"], gadgetMancanti: [], starPowerMancanti: [] },
  "Max": { potenza: 11, trofei: 1017, gadget: ["Phase Shifter"], starPower: ["Super Charged","Run N Gun"], gadgetMancanti: ["Sneaky Sneakers"], starPowerMancanti: [] },
  "Meeple": { potenza: 11, trofei: 1095, gadget: ["Mansions Of Meeple","Ragequit"], starPower: ["Do Not Pass Go","Rule Bending"], gadgetMancanti: [], starPowerMancanti: [] },
  "Meg": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Jolting Volts","Repurpose"], starPowerMancanti: ["Force Field","Heavy Metal"] },
  "Melodie": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Perfect Pitch","Interlude"], starPowerMancanti: ["Fast Beats","Extended Mix"] },
  "Mico": { potenza: 5, trofei: 314, gadget: [], starPower: [], gadgetMancanti: ["Clipping Scream","Presto"], starPowerMancanti: ["Monkey Business","Record Smash"] },
  "Mina": { potenza: 11, trofei: 2003, gadget: ["Windmill","Capo-What?"], starPower: ["Zum Zum Zum","Blown Away"], gadgetMancanti: [], starPowerMancanti: [] },
  "Moe": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Dodgy Digging","Rat Race"], starPowerMancanti: ["Skipping Stones","Speeding Ticket"] },
  "Mortis": { potenza: 11, trofei: 2005, gadget: ["Combo Spinner","Creature Of The Night"], starPower: ["Creepy Harvest","Coiled Snake"], gadgetMancanti: [], starPowerMancanti: [] },
  "Mr. P": { potenza: 1, trofei: 10, gadget: [], starPower: [], gadgetMancanti: ["Service Bell","Porter Reinforcements"], starPowerMancanti: ["Handle With Care","Revolving Door"] },
  "Najia": { potenza: 11, trofei: 2062, gadget: ["Poison Puddles","Najia Jar"], starPower: ["Poisonous Protector","Venomous"], gadgetMancanti: [], starPowerMancanti: [] },
  "Nani": { potenza: 1, trofei: 60, gadget: [], starPower: [], gadgetMancanti: ["Warpin' Time","Return To Sender"], starPowerMancanti: ["Autofocus","Tempered Steel"] },
  "Nita": { potenza: 11, trofei: 2012, gadget: ["Bear Paws","Faux Fur"], starPower: ["Bear With Me","Hyper Bear"], gadgetMancanti: [], starPowerMancanti: [] },
  "Nori": { potenza: 11, trofei: 1631, gadget: ["Sushi Snack","Gonna Need A Bigger Net"], starPower: ["Big Haul","His Mother's Son"], gadgetMancanti: [], starPowerMancanti: [] },
  "Ollie": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Regulate","All Eyez On Me"], starPowerMancanti: ["Kick, Push","Renegade"] },
  "Otis": { potenza: 11, trofei: 1157, gadget: ["Dormant Star","Phat Splatter"], starPower: ["Stencil Glue","Ink Refills"], gadgetMancanti: [], starPowerMancanti: [] },
  "Pam": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Pulse Modulator","Scrapsucker"], starPowerMancanti: ["Mama's Hug","Mama's Squeeze"] },
  "Pearl": { potenza: 5, trofei: 282, gadget: [], starPower: [], gadgetMancanti: ["Overcooked","Made With Love"], starPowerMancanti: ["Heat Retention","Heat Shield"] },
  "Penny": { potenza: 1, trofei: 204, gadget: [], starPower: [], gadgetMancanti: ["Salty Barrel","Trusty Spyglass"], starPowerMancanti: ["Heavy Coffers","Master Blaster"] },
  "Pierce": { potenza: 11, trofei: 2007, gadget: ["Bottomless Mags","You Only Brawl Twice"], starPower: ["Mission: Swimpossible","Slip 'n Snipe"], gadgetMancanti: [], starPowerMancanti: [] },
  "Piper": { potenza: 11, trofei: 1020, gadget: ["Auto Aimer","Homemade Recipe"], starPower: ["Ambush","Snappy Sniping"], gadgetMancanti: [], starPowerMancanti: [] },
  "Poco": { potenza: 5, trofei: 117, gadget: [], starPower: [], gadgetMancanti: ["Tuning Fork","Protective Tunes"], starPowerMancanti: ["Da Capo!","Screeching Solo"] },
  "R-T": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Out Of Line","Hacks!"], starPowerMancanti: ["Quick Maths","Recording"] },
  "Rico": { potenza: 11, trofei: 2010, gadget: ["Multiball Launcher","Multiball"], starPower: ["Super Bouncy","Robo Retreat"], gadgetMancanti: [], starPowerMancanti: [] },
  "Rosa": { potenza: 1, trofei: 145, gadget: [], starPower: [], gadgetMancanti: ["Grow Light","Unfriendly Bushes"], starPowerMancanti: ["Plant Life","Thorny Gloves"] },
  "Ruffs": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Take Cover","Air Support"], starPowerMancanti: ["Air Superiority","Field Promotion"] },
  "Sam": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Magnetic Field","Pulse Repellent"], starPowerMancanti: ["Hearty Recovery","Remote Recharge"] },
  "Sandy": { potenza: 8, trofei: 302, gadget: ["Sleep Stimulator","Sweet Dreams"], starPower: [], gadgetMancanti: [], starPowerMancanti: ["Rude Sands","Healing Winds"] },
  "Shade": { potenza: 11, trofei: 1038, gadget: ["Longarms"], starPower: ["Spooky Speedster","Hardened Hoodie"], gadgetMancanti: ["Jump Scare"], starPowerMancanti: [] },
  "Shelly": { potenza: 10, trofei: 1000, gadget: ["Fast Forward","Clay Pigeons"], starPower: ["Shell Shock","Band-Aid"], gadgetMancanti: [], starPowerMancanti: [] },
  "Sirius": { potenza: 11, trofei: 2000, gadget: ["A Starr Is Born"], starPower: ["Dusk Runners","The Darkest Starr"], gadgetMancanti: ["Master Of Shadows"], starPowerMancanti: [] },
  "Spike": { potenza: 10, trofei: 1120, gadget: ["Popping Pincushion","Life Plant"], starPower: ["Fertilize","Curveball"], gadgetMancanti: [], starPowerMancanti: [] },
  "Sprout": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Garden Mulcher","Transplant"], starPowerMancanti: ["Overgrowth","Photosynthesis"] },
  "Squeak": { potenza: 6, trofei: 251, gadget: [], starPower: [], gadgetMancanti: ["Windup","Residue"], starPowerMancanti: ["Chain Reaction","Super Sticky"] },
  "Starr Nova": { potenza: 11, trofei: 1060, gadget: ["Floaty Time","Shining Starr Of Friendship And Justice"], starPower: ["Power Level: Maximum","Mystical Starr Technique"], gadgetMancanti: [], starPowerMancanti: [] },
  "Stu": { potenza: 11, trofei: 1593, gadget: ["Speed Zone","Breakthrough"], starPower: ["Zero Drag","Gaso-Heal"], gadgetMancanti: [], starPowerMancanti: [] },
  "Surge": { potenza: 11, trofei: 1422, gadget: ["Power Surge","Power Shield"], starPower: ["To The Max!","Serve Ice Cold"], gadgetMancanti: [], starPowerMancanti: [] },
  "Tara": { potenza: 11, trofei: 1015, gadget: ["Psychic Enhancer","Support From Beyond"], starPower: ["Black Portal","Healing Shade"], gadgetMancanti: [], starPowerMancanti: [] },
  "Tick": { potenza: 1, trofei: 145, gadget: [], starPower: [], gadgetMancanti: ["Mine Mania","Last Hurrah"], starPowerMancanti: ["Well Oiled","Automa-Tick Reload"] },
  "Trunk": { potenza: 1, trofei: 36, gadget: [], starPower: [], gadgetMancanti: ["For The Queen!","Worker Ants"], starPowerMancanti: ["New Insect Overlords","Colony Scouts"] },
  "Wendy": { potenza: 11, trofei: 851, gadget: ["Wind-Powered"], starPower: ["Slowing Shield","Solar Shield"], gadgetMancanti: ["Green Grenade"], starPowerMancanti: [] },
  "Willow": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Spellbound","Dive"], starPowerMancanti: ["Love Is Blind","Obsession"] },
  "Ziggy": { potenza: 1, trofei: 0, gadget: [], starPower: [], gadgetMancanti: ["Electric Shuffle","Now You See Me..."], starPowerMancanti: ["Thunderstruck","The Great Ziggini"] },
};
