// Livello di potenza dei brawler del proprietario dell'app.
// GENERATO da script/fetch-profilo-brawl.js — non modificare a mano.
// Letto il 2026-09-08 dal tracker pubblico di brawlplanet.
//
// Per ogni brawler: livello di potenza e trofei.
//
// PERCHÉ SERVE: in Classificata un brawler sotto POTENZA 9 non si può
// schierare, e da Mythic in su ne serve uno a POTENZA 11. Un consiglio su un
// brawler che non puoi mettere in campo è peggio che inutile: fa perdere i
// secondi che non hai. Qui ce ne sono 50 giocabili su 106, 36 a potenza 11.
//
// Il tag del giocatore NON sta qui apposta: questo repository è pubblico.
// È una fotografia: risbloccando o potenziando un brawler va rilanciato.
const PROFILO = {
  "8-Bit": { potenza: 11, trofei: 1000 },
  "Alli": { potenza: 1, trofei: 13 },
  "Amber": { potenza: 9, trofei: 1000 },
  "Angelo": { potenza: 7, trofei: 375 },
  "Ash": { potenza: 9, trofei: 46 },
  "Barley": { potenza: 1, trofei: 124 },
  "Bea": { potenza: 10, trofei: 1362 },
  "Belle": { potenza: 9, trofei: 1006 },
  "Berry": { potenza: 1, trofei: 33 },
  "Bibi": { potenza: 1, trofei: 171 },
  "Bo": { potenza: 11, trofei: 2012 },
  "Bolt": { potenza: 1, trofei: 10 },
  "Bonnie": { potenza: 1, trofei: 46 },
  "Brock": { potenza: 11, trofei: 2003 },
  "Bull": { potenza: 9, trofei: 1005 },
  "Buster": { potenza: 7, trofei: 53 },
  "Buzz": { potenza: 10, trofei: 1006 },
  "Byron": { potenza: 1, trofei: 0 },
  "Carl": { potenza: 11, trofei: 1006 },
  "Charlie": { potenza: 1, trofei: 0 },
  "Chester": { potenza: 11, trofei: 1821 },
  "Chuck": { potenza: 1, trofei: 0 },
  "Clancy": { potenza: 6, trofei: 165 },
  "Colette": { potenza: 10, trofei: 1057 },
  "Colt": { potenza: 11, trofei: 1771 },
  "Cordelius": { potenza: 11, trofei: 1176 },
  "Crow": { potenza: 11, trofei: 2007 },
  "Damian": { potenza: 11, trofei: 1357 },
  "Darryl": { potenza: 1, trofei: 145 },
  "Doug": { potenza: 1, trofei: 0 },
  "Draco": { potenza: 1, trofei: 0 },
  "Dynamike": { potenza: 6, trofei: 150 },
  "Edgar": { potenza: 11, trofei: 1589 },
  "El Primo": { potenza: 5, trofei: 248 },
  "Emz": { potenza: 11, trofei: 2009 },
  "Eve": { potenza: 1, trofei: 0 },
  "Fang": { potenza: 1, trofei: 0 },
  "Finx": { potenza: 1, trofei: 204 },
  "Frank": { potenza: 1, trofei: 0 },
  "Gale": { potenza: 10, trofei: 1011 },
  "Gene": { potenza: 10, trofei: 1006 },
  "Gigi": { potenza: 1, trofei: 0 },
  "Glowy": { potenza: 9, trofei: 820 },
  "Gray": { potenza: 11, trofei: 1012 },
  "Griff": { potenza: 11, trofei: 1619 },
  "Grom": { potenza: 1, trofei: 131 },
  "Gus": { potenza: 11, trofei: 1428 },
  "Hank": { potenza: 1, trofei: 42 },
  "Jacky": { potenza: 1, trofei: 145 },
  "Jae-Yong": { potenza: 1, trofei: 49 },
  "Janet": { potenza: 1, trofei: 0 },
  "Jessie": { potenza: 1, trofei: 145 },
  "Juju": { potenza: 1, trofei: 0 },
  "Kaze": { potenza: 1, trofei: 60 },
  "Kenji": { potenza: 9, trofei: 1001 },
  "Kit": { potenza: 11, trofei: 1192 },
  "Larry & Lawrie": { potenza: 1, trofei: 206 },
  "Leon": { potenza: 11, trofei: 2006 },
  "Lily": { potenza: 7, trofei: 432 },
  "Lola": { potenza: 1, trofei: 111 },
  "Lou": { potenza: 11, trofei: 1042 },
  "Lumi": { potenza: 11, trofei: 2012 },
  "Maisie": { potenza: 6, trofei: 227 },
  "Mandy": { potenza: 9, trofei: 415 },
  "Max": { potenza: 11, trofei: 1017 },
  "Meeple": { potenza: 11, trofei: 1095 },
  "Meg": { potenza: 1, trofei: 0 },
  "Melodie": { potenza: 1, trofei: 0 },
  "Mico": { potenza: 5, trofei: 314 },
  "Mina": { potenza: 11, trofei: 2003 },
  "Moe": { potenza: 1, trofei: 0 },
  "Mortis": { potenza: 11, trofei: 2005 },
  "Mr. P": { potenza: 1, trofei: 10 },
  "Najia": { potenza: 11, trofei: 2062 },
  "Nani": { potenza: 1, trofei: 60 },
  "Nita": { potenza: 11, trofei: 2012 },
  "Nori": { potenza: 11, trofei: 1631 },
  "Ollie": { potenza: 1, trofei: 0 },
  "Otis": { potenza: 11, trofei: 1157 },
  "Pam": { potenza: 1, trofei: 0 },
  "Pearl": { potenza: 5, trofei: 282 },
  "Penny": { potenza: 1, trofei: 204 },
  "Pierce": { potenza: 11, trofei: 2007 },
  "Piper": { potenza: 11, trofei: 1020 },
  "Poco": { potenza: 5, trofei: 117 },
  "R-T": { potenza: 1, trofei: 0 },
  "Rico": { potenza: 11, trofei: 2010 },
  "Rosa": { potenza: 1, trofei: 145 },
  "Ruffs": { potenza: 1, trofei: 0 },
  "Sam": { potenza: 1, trofei: 0 },
  "Sandy": { potenza: 8, trofei: 302 },
  "Shade": { potenza: 11, trofei: 1038 },
  "Shelly": { potenza: 10, trofei: 1000 },
  "Sirius": { potenza: 11, trofei: 2000 },
  "Spike": { potenza: 10, trofei: 1120 },
  "Sprout": { potenza: 1, trofei: 0 },
  "Squeak": { potenza: 6, trofei: 251 },
  "Starr Nova": { potenza: 11, trofei: 1060 },
  "Stu": { potenza: 11, trofei: 1593 },
  "Surge": { potenza: 11, trofei: 1422 },
  "Tara": { potenza: 11, trofei: 1015 },
  "Tick": { potenza: 1, trofei: 145 },
  "Trunk": { potenza: 1, trofei: 36 },
  "Wendy": { potenza: 11, trofei: 851 },
  "Willow": { potenza: 1, trofei: 0 },
  "Ziggy": { potenza: 1, trofei: 0 },
};
